### ISSUE TITLE
Uncaught Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33

### ISSUE THREAD

**Issue by ltfschoen** [zeitgeistpm/sdk-next#47]
When I go to https://app.zeitgeist.pm/ and I try to connect Polkadot.js I get this error
```
Uncaught Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33
    at encodeAddress (_app-e974f4a3eac5c1c3.js:308:52598)
    at _app-e974f4a3eac5c1c3.js:234:499877
    at Array.map (<anonymous>)
    at _app-e974f4a3eac5c1c3.js:234:499845
    at eu.write (_app-e974f4a3eac5c1c3.js:725:1726)
    at writeAtomState (_app-e974f4a3eac5c1c3.js:725:6708)
    at Object.writeAtom [as set] (_app-e974f4a3eac5c1c3.js:725:6782)
    at _app-e974f4a3eac5c1c3.js:234:499744
    at Object.subscriber (_app-e974f4a3eac5c1c3.js:1:102250)
    at page.js:2:82522
```

**Comment by ltfschoen** [comment]
duplicate of https://github.com/zeitgeistpm/ui/issues/2185
